version: '3.4'
services:
  simple_aws_database:
    image: mongo:latest
    # ports:
    #   - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 60s
      timeout: 10s
      start_period: 40s
      retries: 5
  simple_aws_server:
    image: simple_aws_server:latest
    environment:
      DB_HOST: simple_aws_database
    # ports:
    # - "8200:8200"
    depends_on:
    - simple_aws_database
    healthcheck:
      test: node src/healthcheck.js
      interval: 60s
      timeout: 10s
      start_period: 40s
      retries: 5
  simple_aws_client:
    image: simple_aws_client:latest
    environment:
      API_HOST: simple_aws_server
    ports:
      - "4200:80"
    depends_on:
      - simple_aws_server
    healthcheck:
      test: curl -sS http://127.0.0.1 || exit 1
      interval: 60s
      timeout: 10s
      start_period: 40s
      retries: 5
